### ISSUE TITLE
バグあった

### ISSUE THREAD

**Issue by nepia11** [nepia11/blender-gpencil-stroke-normalizer#6]
Python: Traceback (most recent call last):
  File "/home/nepia/dev/BlenderProject/addons/blender-gpencil-stroke-normalizer/__init__.py", line 90, in execute
    state1 = select_state.save()
  File "/home/nepia/dev/BlenderProject/addons/blender-gpencil-stroke-normalizer/gpencil_normalizer.py", line 156, in save
    self._lick(state, _save)
  File "/home/nepia/dev/BlenderProject/addons/blender-gpencil-stroke-normalizer/gpencil_normalizer.py", line 122, in _lick
    func(state["layers"][li], layer)
  File "/home/nepia/dev/BlenderProject/addons/blender-gpencil-stroke-normalizer/gpencil_normalizer.py", line 143, in _save
    max_counts = calc_frames_strokes_max_count(obj.frames)
  File "/home/nepia/dev/BlenderProject/addons/blender-gpencil-stroke-normalizer/gpencil_normalizer.py", line 63, in calc_frames_strokes_max_count
    results_max = np.max(np_counts, axis=0)
  File "<__array_function__ internals>", line 5, in amax
  File "/usr/lib/python3.9/site-packages/numpy/core/fromnumeric.py", line 2705, in amax
    return _wrapreduction(a, np.maximum, 'max', axis, None, out,
  File "/usr/lib/python3.9/site-packages/numpy/core/fromnumeric.py", line 87, in _wrapreduction
    return ufunc.reduce(obj, axis, dtype, out, **passkwargs)
ValueError: zero-size array to reduction operation maximum which has no identity

location: <unknown location>:-1

**Comment by nepia11** [comment]
レイヤーの選択状態にかかわらず、フレームが0個のレイヤーが投げ込まれた時に最大値を求めようとしたが、numpyが要素0個の配列の最大値なんぞ求められないぞと言って起こられる不具合だった

とりあえずフレームが0個のときは最大値は0を返すように修正する
